/*
 * This file is generated by jOOQ.
 */
package com.gemini.mis.entity.items.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "LANGUAGE",
    schema = "ITEMS",
    uniqueConstraints = {
        @UniqueConstraint(name = "CONSTRAINT_CE", columnNames = { "ID" }),
        @UniqueConstraint(name = "CONSTRAINT_C", columnNames = { "CD" })
    }
)
public class Language implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", nullable = false, precision = 7)
    private Integer Id;
    @Column(name = "CD", nullable = false, length = 2)
    private String  Cd;
    @Column(name = "DESCRIPTION", length = 50)
    private String  Description;

    public Language() {}

    public Language(Language value) {
        this.Id = value.Id;
        this.Cd = value.Cd;
        this.Description = value.Description;
    }

    @ConstructorProperties({ "Id", "Cd", "Description" })
    public Language(
        Integer Id,
        String  Cd,
        String  Description
    ) {
        this.Id = Id;
        this.Cd = Cd;
        this.Description = Description;
    }

    /**
     * Getter for <code>ITEMS.LANGUAGE.ID</code>.
     */
    public Integer getId() {
        return this.Id;
    }

    /**
     * Setter for <code>ITEMS.LANGUAGE.ID</code>.
     */
    public void setId(Integer Id) {
        this.Id = Id;
    }

    /**
     * Getter for <code>ITEMS.LANGUAGE.CD</code>.
     */
    @NotNull
    @Size(max = 2)
    public String getCd() {
        return this.Cd;
    }

    /**
     * Setter for <code>ITEMS.LANGUAGE.CD</code>.
     */
    public void setCd(String Cd) {
        this.Cd = Cd;
    }

    /**
     * Getter for <code>ITEMS.LANGUAGE.DESCRIPTION</code>.
     */
    @Size(max = 50)
    public String getDescription() {
        return this.Description;
    }

    /**
     * Setter for <code>ITEMS.LANGUAGE.DESCRIPTION</code>.
     */
    public void setDescription(String Description) {
        this.Description = Description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Language (");

        sb.append(Id);
        sb.append(", ").append(Cd);
        sb.append(", ").append(Description);

        sb.append(")");
        return sb.toString();
    }
}
