/*
 * This file is generated by jOOQ.
 */
package com.gemini.ims.entity.items.tables.daos;


import com.gemini.ims.entity.items.tables.Country;
import com.gemini.ims.entity.items.tables.records.CountryRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


import org.jooq.impl.DefaultConfiguration;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class CountryDao extends DAOImpl<CountryRecord, com.gemini.ims.entity.items.tables.pojos.Country, Integer> {

    /**
     * Create a new CountryDao without any configuration
     */
    public CountryDao() {
        super(Country.COUNTRY, com.gemini.ims.entity.items.tables.pojos.Country.class);
    }

    /**
     * Create a new CountryDao with an attached configuration
     */
    @Autowired
    public CountryDao(Configuration configuration) {
        super(Country.COUNTRY, com.gemini.ims.entity.items.tables.pojos.Country.class, configuration);
    }

    @Override
    public Integer getId(com.gemini.ims.entity.items.tables.pojos.Country object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gemini.ims.entity.items.tables.pojos.Country> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Country.COUNTRY.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.gemini.ims.entity.items.tables.pojos.Country> fetchById(Integer... values) {
        return fetch(Country.COUNTRY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.gemini.ims.entity.items.tables.pojos.Country fetchOneById(Integer value) {
        return fetchOne(Country.COUNTRY.ID, value);
    }

    /**
     * Fetch records that have <code>NAME BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gemini.ims.entity.items.tables.pojos.Country> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Country.COUNTRY.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>NAME IN (values)</code>
     */
    public List<com.gemini.ims.entity.items.tables.pojos.Country> fetchByName(String... values) {
        return fetch(Country.COUNTRY.NAME, values);
    }

    /**
     * Created custom fetchRecord Method
     */
    public com.gemini.ims.entity.items.tables.pojos.Country fetchRecord(Integer Id){
            return this.ctx().selectFrom(Country.COUNTRY).where(Country.COUNTRY.ID.eq(Id)).fetchOneInto(com.gemini.ims.entity.items.tables.pojos.Country.class);
            }

            /**
             * Created custom Insert records Method
             */
            public com.gemini.ims.entity.items.tables.pojos.Country insertRecord(com.gemini.ims.entity.items.tables.pojos.Country classObject) {
                CountryRecord record=this.ctx().newRecord(Country.COUNTRY);
                record.setName(classObject.getName());
                record.store();
                com.gemini.ims.entity.items.tables.pojos.Country result=record.into(com.gemini.ims.entity.items.tables.pojos.Country.class);
                return result;
            }

            /**
             * Created custom Delete record Method
             */
            public int deleteRecord(Integer Id){
                int result=this.ctx().deleteFrom(Country.COUNTRY).where(Country.COUNTRY.ID.eq(Id)).execute();
                return result;
            }

            /**
             * Created custom Update record Method
             */
            public int updateRecord(com.gemini.ims.entity.items.tables.pojos.Country classObject){
                int result=this.ctx().update(Country.COUNTRY)
                .set(Country.COUNTRY.NAME,classObject.getName())
                .where(Country.COUNTRY.ID.eq(classObject.getId())).execute();
                return result;
            }
        }
