/*
 * This file is generated by jOOQ.
 */
package com.gemini.mis.entity.items;


import com.gemini.mis.entity.DefaultCatalog;
import com.gemini.mis.entity.items.tables.Author;
import com.gemini.mis.entity.items.tables.Book;
import com.gemini.mis.entity.items.tables.Language;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Items extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ITEMS</code>
     */
    public static final Items ITEMS = new Items();

    /**
     * The table <code>ITEMS.AUTHOR</code>.
     */
    public final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>ITEMS.BOOK</code>.
     */
    public final Book BOOK = Book.BOOK;

    /**
     * The table <code>ITEMS.LANGUAGE</code>.
     */
    public final Language LANGUAGE = Language.LANGUAGE;

    /**
     * No further instances allowed
     */
    private Items() {
        super("ITEMS", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            Book.BOOK,
            Language.LANGUAGE);
    }
}
