/*
 * This file is generated by jOOQ.
 */
package com.gemini.mis.entity.items;


import com.gemini.mis.entity.items.tables.Author;
import com.gemini.mis.entity.items.tables.Book;
import com.gemini.mis.entity.items.tables.Language;
import com.gemini.mis.entity.items.tables.records.AuthorRecord;
import com.gemini.mis.entity.items.tables.records.BookRecord;
import com.gemini.mis.entity.items.tables.records.LanguageRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * ITEMS.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorRecord> CONSTRAINT_7 = Internal.createUniqueKey(Author.AUTHOR, DSL.name("CONSTRAINT_7"), new TableField[] { Author.AUTHOR.ID }, true);
    public static final UniqueKey<BookRecord> CONSTRAINT_1 = Internal.createUniqueKey(Book.BOOK, DSL.name("CONSTRAINT_1"), new TableField[] { Book.BOOK.ID }, true);
    public static final UniqueKey<LanguageRecord> CONSTRAINT_C = Internal.createUniqueKey(Language.LANGUAGE, DSL.name("CONSTRAINT_C"), new TableField[] { Language.LANGUAGE.CD }, true);
    public static final UniqueKey<LanguageRecord> CONSTRAINT_CE = Internal.createUniqueKey(Language.LANGUAGE, DSL.name("CONSTRAINT_CE"), new TableField[] { Language.LANGUAGE.ID }, true);
}
