/*
 * This file is generated by jOOQ.
 */
package com.gemini.mis.entity.items;


import com.gemini.mis.entity.items.tables.Author;
import com.gemini.mis.entity.items.tables.Book;
import com.gemini.mis.entity.items.tables.Language;


/**
 * Convenience access to all tables in ITEMS.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ITEMS.AUTHOR</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>ITEMS.BOOK</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>ITEMS.LANGUAGE</code>.
     */
    public static final Language LANGUAGE = Language.LANGUAGE;
}
