/*
 * This file is generated by jOOQ.
 */
package com.gemini.ims.entity.items.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "COUNTRY",
    schema = "ITEMS",
    uniqueConstraints = {
        @UniqueConstraint(name = "CONSTRAINT_6", columnNames = { "ID" })
    }
)
public class Country implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", nullable = false, precision = 7)
    private Integer Id;
    @Column(name = "NAME", nullable = false, length = 400)
    private String  Name;

    public Country() {}

    public Country(Country value) {
        this.Id = value.Id;
        this.Name = value.Name;
    }

    @ConstructorProperties({ "Id", "Name" })
    public Country(
        Integer Id,
        String  Name
    ) {
        this.Id = Id;
        this.Name = Name;
    }

    /**
     * Getter for <code>ITEMS.COUNTRY.ID</code>.
     */
    public Integer getId() {
        return this.Id;
    }

    /**
     * Setter for <code>ITEMS.COUNTRY.ID</code>.
     */
    public void setId(Integer Id) {
        this.Id = Id;
    }

    /**
     * Getter for <code>ITEMS.COUNTRY.NAME</code>.
     */
    @NotNull
    @Size(max = 400)
    public String getName() {
        return this.Name;
    }

    /**
     * Setter for <code>ITEMS.COUNTRY.NAME</code>.
     */
    public void setName(String Name) {
        this.Name = Name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Country (");

        sb.append(Id);
        sb.append(", ").append(Name);

        sb.append(")");
        return sb.toString();
    }
}
